services:
  - type: pserv # Приватный сервис (Private Service)
    name: exchange-rates-service
    env: go
    buildCommand: go build -o bin/server ./cmd/server
    startCommand: ./bin/server -c config.env
    envVars:
      - key: GRPC_PORT
        value: 50051
      - key: DB_HOST
        sync: false # Укажите вручную в Render Dashboard
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        sync: false # Укажите вручную
      - key: DB_PASSWORD
        sync: false # Укажите вручную
      - key: DB_NAME
        sync: false # Укажите вручную
      - key: LOG_LEVEL
        value: info